name = "Wytheria ModPack"
author = "Wytheria"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f7bbabae113c2d0d49439f10a31a9c4940574999e57824a18631bd3562fb61d"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
