name = "Wytheria ModPack"
author = "Wytheria"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d3c96fbe7b69f36c9ca56669c7a056af69a787074374bdf22cef2bad1328854"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
